### ISSUE TITLE
Percent sign causes invalid output in secrets

### ISSUE THREAD

**Issue by argestes** [bitrise-io/go-steputils#17]
I'm using apk signer step on an Android Build. Unfortunately my private key password contains a percent sign (%). While trying to use that password my build failed since % was replaced with `%!(MISSING)` annotation hence changing private key password, which causes build failure.

**Comment by non-binary** [comment]
Hi @argestes,

Thank you for reaching out.

Can you please share a link to a build that reproduces this behaviour?

Thanks,
Luna
